AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Fetches jumoresques and reads them out loud in funny voice
Resources:
  AnimalsBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt CsvSqs.Arn
    DependsOn: CsvSqsPolicy
  CsvSqs:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CsvDeadLetterSqs.Arn
        maxReceiveCount: 1
  CsvDeadLetterSqs:
    Type: AWS::SQS::Queue
  CsvSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Resource:
              - !GetAtt CsvSqs.Arn
            Action:
              - SQS:SendMessage
      Queues:
        - !Ref CsvSqs
  AnimalSqs:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AnimalDeadLetterSqs.Arn
        maxReceiveCount: 10
  AnimalDeadLetterSqs:
    Type: AWS::SQS::Queue
  ClassificationDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: type
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ReadAnimals:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
      Runtime: java11
      CodeUri: target/serverless-map-reduce-java-0.0.1-SNAPSHOT-aws.jar
      Policies:
        - S3ReadPolicy:
            BucketName:
              !Ref AnimalsBucket
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt AnimalSqs.QueueName
        - SQSPollerPolicy:
            QueueName:
              !GetAtt CsvSqs.QueueName
      Events:
        PutCsv:
          Type: SQS
          Properties:
            Queue: !GetAtt CsvSqs.Arn
            BatchSize: 1
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          SQS_TOPIC: !Ref AnimalSqs
          DYNAMO_TABLE: !Ref ClassificationDynamoTable
          SPRING_PROFILES_ACTIVE: aws,read
  ReadAnimalsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ReadAnimals
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::amimals-bucket
  ClassifyAnimals:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.serverlessmapreducejava.SqsEventHandler
      Runtime: java11
      CodeUri: target/serverless-map-reduce-java-0.0.1-SNAPSHOT-aws.jar
      Policies:
        - DynamoDBWritePolicy:
            TableName:
              !Ref ClassificationDynamoTable
        - SQSPollerPolicy:
            QueueName:
              !GetAtt AnimalSqs.QueueName
      Events:
        AnimalQueued:
          Type: SQS
          Properties:
            Queue: !GetAtt AnimalSqs.Arn
            BatchSize: 1
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref ClassificationDynamoTable
          SPRING_PROFILES_ACTIVE: aws,classify
          SQS_TOPIC: !Ref AnimalSqs
